/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tp5.theatre;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Lucas
 */
public class GraphicInterface extends javax.swing.JFrame {

    Client cl;

    /**
     * Creates new form GraphicInterface
     */
    public GraphicInterface() throws UnknownHostException, IOException {
        cl = new Client();
        initComponents();
        // on reccupere la liste des "films" et on les met dans un arrayList
        ArrayList<String> list = cl.getList();
        userChoice.setModel(new javax.swing.DefaultComboBoxModel(list.toArray())); // on met dans le combobox "userchoice" la liste
        numberSeats.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"1", "2", "3", "4", "5"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        labelMoovie = new javax.swing.JLabel();
        labelNumber = new javax.swing.JLabel();
        userChoice = new javax.swing.JComboBox();
        numberSeats = new javax.swing.JComboBox();
        validate = new javax.swing.JButton();
        reponseServer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name.setText("Entrez votre nom");

        labelMoovie.setText("Quel film voulez-vous voir ?");

        labelNumber.setText("Combien de place souhaitez-vous ?");

        userChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        numberSeats.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        validate.setText("Valider");
        validate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validateMouseClicked(evt);
            }
        });
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMoovie)
                            .addComponent(Name)
                            .addComponent(labelNumber))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 236, Short.MAX_VALUE))
                    .addComponent(reponseServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(validate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMoovie)
                    .addComponent(userChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumber)
                    .addComponent(numberSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(validate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reponseServer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validateActionPerformed
// ce qu'il se passe lorsque l'on clique sur le bouton "Valider"
    private void validateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validateMouseClicked
        String namestr = userName.getText();
        String piecestr = userChoice.getSelectedItem().toString();
        int number = Integer.parseInt(numberSeats.getSelectedItem().toString());
        int diff = cl.reserver(namestr, piecestr, number);
        if (diff >= 0) {
            reponseServer.setText("Vous avez réservé " + number + " place(s) pour voir " + piecestr + " sous le nom de: " + namestr);
        } else {
            if (diff == Integer.MIN_VALUE) {
                reponseServer.setText("Une erreur s'est produite pendant la réservation.");
            } else {
                reponseServer.setText("Impossible d'effectuer la réservation : il manque " + Math.abs(diff) + " place(s)");
            }
        }
    }//GEN-LAST:event_validateMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel labelMoovie;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JComboBox numberSeats;
    private javax.swing.JLabel reponseServer;
    private javax.swing.JComboBox userChoice;
    private javax.swing.JTextField userName;
    private javax.swing.JButton validate;
    // End of variables declaration//GEN-END:variables
}
